name: 02-conf_variables
run-name: conf_variables
# first you have set them in project->setting->actions->variables
on: 
  workflow_dispatch
env:
  cloud: google-cloud
jobs:
  gretting_job:
    runs-on: ubuntu-latest
    env: 
      greeting: hello
    steps:
      - name: "say hello from the cloud"
      # to access this variables you have to use double curly braces
        run: echo "$greeting $first_name is using $cloud on project id ${{vars.id}}"
        env:
          first_name: Ishan 