name: 03-input_variables
run-name: input_variables
on: 
  workflow_dispatch:
    inputs:
      num1:
        description: "number1"
        type: number
        default: "0"
        required: true
      num2:
        description: "number2"
        type: number
        default: "0"
        required: true
jobs:
  gretting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "practice on input var"
        run: echo ${{inputs.num1}}+${{inputs.num2}}